name: MGT 304
favicon: null
layout_spectrum: 0.87622
typography_spectrum: 0.9328
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.375
  lightness: 0.25
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
