name: MGT 304
favicon: null
layout_spectrum: 0.87622
typography_spectrum: 0.9328
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cbdddf'
    - '#0e151d'
    - '#a1babe'
    - '#799ea7'
    - '#456965'
  brandStrength: 0.625
  lightness: 0.0625
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
