name: MGT 304
favicon: null
layout_spectrum: 0
typography_spectrum: 0.9328
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.24248994630761445
  lightness: 0.9164935636799783
  saturation: 0.3570172206964344
  rhythmicContrast: 0.1404202221892774
purpose: []
