name: MGT 304
favicon: null
layout_spectrum: 0.00993
typography_spectrum: 0.94742
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cbdddf'
    - '#0e151d'
    - '#a1babe'
    - '#799ea7'
    - '#456965'
  brandStrength: 0.5625
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
